require("heroes.paladin.Q")
require("heroes.paladin.W")
require("heroes.paladin.E")
require("heroes.paladin.R")
require("heroes.paladin.HeroInit")

require("heroes.warden.Q")
require("heroes.warden.W")
require("heroes.warden.E")
require("heroes.warden.R")
require("heroes.warden.HeroInit")

require("heroes.evilsylvanas.Q")
require("heroes.evilsylvanas.W")
require("heroes.evilsylvanas.E")
require("heroes.evilsylvanas.R")
require("heroes.evilsylvanas.HeroInit")

require("heroes.murlocyellow.Q")
require("heroes.murlocyellow.W")
require("heroes.murlocyellow.E")
require("heroes.murlocyellow.R")
require("heroes.murlocyellow.HeroInit")

require("heroes.ratling.Q")
require("heroes.ratling.W")
require("heroes.ratling.E")
require("heroes.ratling.R")
require("heroes.ratling.HeroInit")

require("heroes.seawitch.Q")
require("heroes.seawitch.W")
require("heroes.seawitch.E")
require("heroes.seawitch.R")
require("heroes.seawitch.HeroInit")